### ISSUE TITLE
Using Bootstrap

### ISSUE THREAD

**Issue by MakamuEvans** [maoberlehner/skeleton-loading-animation-with-vue#1]
Hi, am trying to use bootstrap and cant seem to place like three skeleton on one line to emulate like table columns......each skeleton instance is pushed to the next line

**Comment by maoberlehner** [comment]
Hello @MakamuEvans, that's unfortunate. But I guess I can't help you without any further details 🤔

**Comment by MakamuEvans** [comment]
Found a work around, Thanks tho
